<a href="https://colab.research.google.com/github/saywhypablo/laba2024/blob/main/reps/rep3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторная работа №3. NumPy

## Задание

Выполните следующие задания:

1. Откройте в файл в Google Colab (используйте собственный форк репозитория).
2. Решите задачи.
3. Сохраните результат в ваш репозиторий github в директорию ./les03
4. Создайте pull request в репозиторий https://github.com/chebotarevsa/dap-2024. Название pull request должно иметь формат "<Номер лабораторной работы>  <Номер группы> <ФИО>"
5. Сдайте работу в системе "Пегас", в отчет укажите ссылку на pull request

In [ ]:
import numpy as np
np.version.version

'1.26.4'

1. Создать массив 10x10 со случайными значениями, найти минимум и максимум (низкая)

In [ ]:
import numpy as np
array = np.random.randint(1, 100, (10, 10))
print("\nCreated array: \n\n", array)
print("\nMinimum of the array is", array.min())
print("Maximum of the array is", array.max())


Created array: 

 [[70 15 72 94 53 46 92 76 77 18]
 [98 71 12 10 91 48 43  4  8 45]
 [18 18 49 54 88 10 52 93 52 92]
 [52 65 98 63 68 31 87 21 14 77]
 [99 59 56 85 99 43 11 61 26 71]
 [75 66 30 73 34 50 23 45 79 90]
 [41  2 16 48  3 67 41 21 48 18]
 [85 37 49 74 22 48 38 69 15 96]
 [19 28 84 13 90 28 59  7 97 59]
 [ 5 47  9 37 78 83 27 52 44 38]]

Minimum of the array is 2
Maximum of the array is 99


2. Создать 8x8 матрицу и заполнить её единицами и нулями в шахматном порядке

In [ ]:
import numpy as np
matrix = np.zeros((8,8))
matrix[::2, 1::2] = 1
matrix[1::2, ::2] = 1
print("Created matrix in a checkerboard order: \n", matrix)

Created matrix in a checkerboard order: 
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


3. Дан массив из 11 элементов, поменять знак у элементов, значения которых между 3 и 8

In [ ]:
import numpy as np
z = np.arange(11)
print("Given array:\n", z)
z[(z > 3) & (z < 8)] *= -1
print("Resulted array:\n", z)

Given array:
 [ 0  1  2  3  4  5  6  7  8  9 10]
Resulted array:
 [ 0  1  2  3 -4 -5 -6 -7  8  9 10]


4. Найти среднее значение строки матрицы и вычесть его из каждого елемента строки

In [ ]:
import numpy as np
z = np.random.rand(5, 10)
print("Given matrix: \n", z)
means = np.mean(z, axis=1, keepdims=True)
z[:, :9] -= means
print("\nMeans:\n", means.reshape(-1))
print("\nResulted matrix:\n", z)

Given matrix: 
 [[0.46569357 0.1815465  0.80316938 0.20348643 0.33992465 0.46167007
  0.28560155 0.49593624 0.98945756 0.87279392]
 [0.63308917 0.01705331 0.2310777  0.89429256 0.94588741 0.43573295
  0.52776255 0.78609565 0.03735222 0.5305422 ]
 [0.35409233 0.36385542 0.21051265 0.95066802 0.96986513 0.07382601
  0.30795656 0.08373884 0.45135231 0.27156606]
 [0.82128302 0.89571537 0.23433549 0.17894688 0.75733436 0.35934592
  0.53424108 0.54642176 0.87790331 0.38755212]
 [0.23552279 0.42007969 0.84959688 0.63950705 0.41591213 0.60183995
  0.62425637 0.50742447 0.60021787 0.74054176]]

Means:
 [0.50992799 0.50388857 0.40374333 0.55930793 0.56348989]

Resulted matrix:
 [[-0.04423441 -0.32838149  0.29324139 -0.30644156 -0.17000334 -0.04825792
  -0.22432643 -0.01399175  0.47952957  0.87279392]
 [ 0.1292006  -0.48683526 -0.27281087  0.39040399  0.44199883 -0.06815562
   0.02387397  0.28220708 -0.46653635  0.5305422 ]
 [-0.049651   -0.03988792 -0.19323069  0.54692468  0.5661218  -0.32991732

5. Поменяйте 1 и 2 строки матрицы

In [ ]:
import numpy as np
z = np.arange(25).reshape(5,5)
print("Given matrix:\n", z)
z[[1, 2]] = z[[2, 1]]
print("\nResulted matrix:\n", z)

Given matrix:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Resulted matrix:
 [[ 0  1  2  3  4]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [15 16 17 18 19]
 [20 21 22 23 24]]


6. Дан массив 10x2 подеставлющий собой точки в декартовой системе координат, преобразовать в полярную

In [ ]:
import numpy as np
z = np.random.random((10, 2))
print("Cartesian coordinates:\n", z)
x = z[:, 0]
y = z[:, 1]
r = np.sqrt(x ** 2 + y ** 2)
phi = np.arctan2(y, x)
pz = np.column_stack((r, phi))
print("\nPolar coordinates (rad):\n", pz)

Cartesian coordinates:
 [[0.32178997 0.0937008 ]
 [0.75365163 0.66358606]
 [0.5453651  0.35832349]
 [0.96719143 0.62511361]
 [0.58869505 0.51371142]
 [0.47786978 0.41163886]
 [0.46133253 0.04401076]
 [0.69408954 0.72432048]
 [0.73975482 0.96465745]
 [0.91598625 0.43933342]]

Polar coordinates (rad):
 [[0.33515463 0.28335125]
 [1.00415996 0.72193343]
 [0.65254794 0.58130424]
 [1.15161898 0.57378274]
 [0.78132022 0.71748463]
 [0.6307187  0.71107743]
 [0.46342707 0.09511138]
 [1.00319512 0.80670819]
 [1.21564847 0.91659341]
 [1.01589598 0.44721827]]


7. Заменить максимальный элемент массива на ноль

In [ ]:
import numpy as np
z = np.random.random(10)
print("Given array:\n", z)
max = np.argmax(z)
print("\nIndex of the maximum element:", max)
z[max] = 0
print("\nResulted array:\n", z)

Given array:
 [0.71749159 0.19894109 0.0730445  0.11065191 0.95350267 0.79382426
 0.03769261 0.2845962  0.33925691 0.36217231]

Index of the maximum element: 4

Resulted array:
 [0.71749159 0.19894109 0.0730445  0.11065191 0.         0.79382426
 0.03769261 0.2845962  0.33925691 0.36217231]


8. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве. Добавление производиться только 1 раз

In [ ]:
import numpy as np
z = np.ones(10)
i = np.random.randint(0,len(z),20)
print("Given array:\n", z)
print("\nGiven indices:\n", i)
unique = np.unique(i)
z[unique] += 1
print("\nResulted array:\n", z)

Given array:
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

Given indices:
 [5 4 6 0 9 2 5 5 2 3 9 0 4 4 1 9 1 0 1 0]

Resulted array:
 [2. 2. 2. 2. 2. 2. 2. 1. 1. 2.]


9. Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [ ]:
import numpy as np
z = np.array([1,2,3,4,5])
print("Given array:\n", z)
x = np.zeros(len(z) + (len(z) - 1) * 3)
x[::4] = z
print("\nResulted array:\n", x)

Given array:
 [1 2 3 4 5]

Resulted array:
 [1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


10. Найти ближайшее к заданному значению число в заданном массиве

In [ ]:
import numpy as np
z = np.arange(100)
v = np.random.uniform(0,100)
print("Given array:\n", z)
print("\nGiven number:", v)
x = np.fabs(z - v).argmin()
y = z[x]
print("\nClosest number to", v, "is", y)

Given array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]

Given number: 45.35074331620309

Closest number to 45.35074331620309 is 45


## Вопросы




**1**. Какой тип (dtype) будут иметь элементы массива?
``` python
np.array([1, 4, 2, 5, 3])
np.array([1., 4, 2, 5, 3])
np.array([1, 4, 2, 5, 3], dtype='float128')
np.array([1., 4, 2, 5, 3], dtype='complex128')
np.array([1, 4, 2, 5, 3], dtype ='float64')
np.array([1, 4, 2, 5, 3], dtype =int64)
np.array([1, 4, 2, 5, 3], dtype='bool')
np.array([1, 4, 2, 5, 3], dtype='str')
np.array([1, 4, 2, 5, '3'])
np.array([1, -4, 2, 0, 1j])
```

**2**. Что будет выведено в консоль и почему?
``` python
np.array([1, 4, 2, 5, 3], dtype='str')[1] + '1'
np.array([1, -4, 2, 0, 3], dtype='bool')[3] or np.array([1, -4, 2, 0, 3])[1]
np.array([1, -4, 2, 0, 3], dtype='bool')[3] and np.array([1, -4, 2, 0, 3])[1]
np.array([1, -4, 2, 0, True], dtype='int64')[-1]
np.array([1, -4, 2, 0, 1j], dtype='int64')[1]
np.array([1, -4, 2, 0, 1j], dtype='str')[-1]
np.array([1, 4, 2, 5, '3'])[-1] * 3
```

**3**. Каков результат операции?

``` python
np.ones((3, 5), dtype=float)
np.full((3, 5), 3.14)
np.linspace(0, 1, 5)
np.diag((1,3,5))
np.smile((1,3,5))
np.random.random((3, 3))
np.eye(3)
np.empty(3)
```



**4**. Дан двумерный массив X, что будет выведено в консоль?

``` python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])
```

``` python
X[0,0]
X[-1,-1]
X[0:1,-1]
X[0:2,-1]
X[0:2,0:2]
X[1,1:3]
X[1,:]
X[1,:]
X[:,:]
X[:]
X[::2,::2]
X[0:3:2,0:3:2]
X[::-1,::-1]
```

**5**. Дан двумерный массив grid, в чем различее между операциями?


``` python
grid = np.arange(16).reshape((4, 4))
```

``` python
np.split(grid, [2])
np.split(grid, [2], axis=1)
```


**6**. В чем различие между операциями?

``` python
    [1, 2, 3] + [3, 2, 1]
    np.array([1, 2, 3]) + np.array([3, 2, 1])
```

**7**. Как в CodeLab измерить время выполнения кода?

**8**. Дан массив X, каковы результаты операций?

```python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])

np.sum(M)
np.sum(M, axis=1)
np.sum(M, axis=0)
np.sum(M, axis=2)
np.sum(M, 1)
sum(M)
sum(M,1)
```

**9**. Дан массив X, что будет выведено в консоль?

```python
X = np.array([1,2,3,4])

X > 3
X < 3
X[X < 3]
X[X > 3]
X[X != 3]
```

**10**.  В чем преимущество массивов NumPy по сравнению с обычными списками.  Чем обусловлено это преимущество?